# Generated by Django 4.2.10 on 2024-03-04 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('season', models.IntegerField()),
                ('episode_num', models.IntegerField()),
                ('watch_date', models.DateField()),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.show')),
            ],
        ),
    ]
