# Generated by Django 4.2.10 on 2024-03-04 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_episode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='watch_date',
            new_name='date',
        ),
    ]
