# Generated by Django 4.2.10 on 2024-03-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_watch_date_episode_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='episode',
            name='date',
            field=models.DateField(verbose_name='Watch Date'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_num',
            field=models.IntegerField(verbose_name='Episode Number'),
        ),
    ]
