# Generated by Django 4.2.11 on 2024-03-04 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_episode_options_alter_episode_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('show', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.show')),
            ],
        ),
    ]
