# Generated by Django 4.2.11 on 2024-03-05 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['name']},
        ),
    ]
