# Generated by Django 4.2.11 on 2024-03-07 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_show_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['-date', '-episode_num']},
        ),
    ]
